config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'home/about'

  get 'home/contact'
    
root 'home#about'
    
get 'home/brochure'
get 'home/company'
get 'home/litigation'
get 'home/staff'
get 'home/services'
get 'home/download_pdf'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

def company 
end

def litigation
end

def services
end
    
def staff
end
    
def brochure
end
    

def download_pdf
  send_file(
    "#{Rails.root}/public/riskbrochure.pdf",
    filename: "riskbrochure.pdf",
    type: "application/pdf"
  )
end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h2 style="color:Maroon;">Independent Risk Management Consultants and Insurance Advisors</h2>
<p>Risk Resources is an independent risk management and commercial insurance consulting firm.Risk Resources does not sell insurance, nor is it associated with any insurance company, brokerage or agency. Our only business is to render objective advice on a fee-for-service basis </p>

    
<p>Risk Resources' history of providing risk management and insurance consulting services dates back to 1898 through our affiliate, Corporate Policyholders Counsel, Inc. Risk Resources has evolved over the years in name and expertise to keep pace in meeting our clients' risk management and insurance needs.</p>


<p>Our consultants individually possess over twenty years of insurance industry experience on average, with the last ten years in a consulting environment. This allows us to bring a broad vision and scope of solutions to client projects using traditional and non-traditional approaches.</p>


<p>As independent consultants, Risk Resources does not sell insurance. We are not associated with any insurance company, brokerage, agency, actuary or self-insurance service organization. Like your accountant or attorney, Risk Resources operates on a fee basis. Our compensation is not based on commissions. This allows us to be totally objective in our analysis and recommendations.
<hr>
<p><%= link_to 'Download our Brochure', home_download_pdf_url %></p>

app/views/home/company.html.erb
<h2 style="color:Maroon;">Longevity</h2>
<p>Risk Resources' history of providing risk management and insurance consulting services dates back to 1898 through our affiliate, Corporate Policyholders Counsel, Inc. Risk Resources has evolved over the years in name and expertise to keep pace in meeting our clients' risk management and insurance needs.</p>


<h2 style="color:Maroon;">Expertise</h2>
<p>Our consultants individually possess over twenty years of insurance industry experience on average, with the last ten years in a consulting environment. This allows us to bring a broad vision and scope of solutions to client projects using traditional and non-traditional approaches.</p>

<h2 style="color:Maroon;">Independence / Objectivity / Integrity</h2>

<p>As independent consultants, Risk Resources does not sell insurance. We are not associated with any insurance company, brokerage, agency, actuary or self-insurance service organization. Like your accountant or attorney, Risk Resources operates on a fee basis. Our compensation is not based on commissions. This allows us to be totally objective in our analysis and recommendations.</p>

app/views/home/contact.html.erb
 <h1  style="color:Maroon;">
Risk Resources</h1>
      <p> 410 N Spring Avenue<br/>
        LaGrange Park, IL 60526 </p>
            <p>Phone: (630) 617-5100 <br/>
</p>
            <p>E-mail: <a href="http://web.archive.org/web/20160429054301/mailto:consultant@riskresources.net">consultant@riskresources.net</a></p>

app/views/home/index.html.erb
<h1>MSRelief</h1>
<p>Licensing nightmares turned into success stories</p>

app/views/home/litigation.html.erb
  <div id="contentWrapper">
    <div id="content"><!-- InstanceBeginEditable name="EditRegion3" -->
      <h1  style="color:Maroon;">Services Overview </h1>
      <p>Our litigation support services are directed towards the attorney whose           practice involves property or liability insurance related issues. We provide           a variety of services at various stages of a dispute or lawsuit. By making           available these resources, the attorney can obtain highly competent counsel           without incurring the expense of maintaining in-house professional staff.           We possess particular expertise in coverage/policy terms interpretation           and industry practices. </p>
      <h1  style="color:Maroon;">Coverage Interpretation </h1>
      <p>Insurance policies and related documents commonly include coverages,           terms, conditions, exclusions and limitations which are difficult to understand           even to professionals within the insurance field. We make the attorney           specifically aware of the special meanings of terms and interpret how           the various policy coverage components mesh together. </p>
      <h1  style="color:Maroon;">Industry Practices </h1>
      <p>The business of insurance is conducted in accordance with industry customs           and practices, some of which may have evolved over decades or even centuries.           The collective experiences of our consulting staff and an insurance library           over a century old are important resources to an attorney. </p>
      <h1  style="color:Maroon;">Litigation </h1>
      <p>When a dispute can't be resolved without litigation, we can assist an           attorney in different ways depending upon individual circumstances. These           include the following: </p>
      <ul>
        <li>Organize and analyze insurance related documents <br/>
        </li>
        <li>Conduct custom research using internal and external reference sources             and databases <br/>
        </li>
        <li>Assist in the development of litigation strategies <br/>
        </li>
        <li>Review draft complaint to ensure technical portions relating to insurance             are correct and relevant documents and parties are referenced appropriately <br/>
        </li>
        <li>Assist in the pre-discovery phase to assess which documents are needed,             who should be deposed and for what information, and who are the important             witnesses and experts needed <br/>
        </li>
        <li>Assist in preparing deponents and witnesses <br/>
        </li>
        <li>Presentation of testimony at trial </li>
      </ul>
    <!-- InstanceEndEditable --></div>
  </div>

app/views/home/staff.html.erb
<h2 style="color:Maroon;">Project Managers</h2>
<hr>
    <h3 style="color:Maroon;">Steven A. Combs</h3>
<hr>
<%= image_tag("steven.jpg", size: "100x113", :style => 'position: relative;',:style => "border: 3px solid Maroon")%>
<p>  </p>
        <li>Twenty-eight years insurance/risk management consulting</li>
          <li>Six years prior underwriting experience with major insurance company </li>
          <li>Western Michigan University (BBA); DePaul University (MA) with concentration in Risk Management/Insurance </li>
          <li>Chartered Property Casualty Underwriter (CPCU) </li>
          <li>Associate in Risk Management (ARM) </li>
          <li>Past President of Society of Risk Management Consultants</li>
<hr>    
<h3 style="color:Maroon;">Randy C. DeLopst</h3>
<hr>

<%= image_tag("randy.jpg", size: "100x113", :style => 'position: relative;',:style => "border: 3px solid Maroon")%>
<p>  </p>
      
          <li>Twenty-seven years insurance/risk management consulting </li>
          <li>Five years prior experience with an international insurance company 
            and as an insurance broker </li>
          <li>University of Wisconsin-Madison (BBA; MBA with concentration in 
            Risk Management/Insurance) </li>
          <li>Chartered Property Casualty Underwriter (CPCU)</li>
          <li>Past President Charter Property and Casualty  Underwriters, Madison, WI Chapter</li>
          <li>Member of the Society of Risk Management Consultants</li>
          <li>Past National Director of Society of Risk Management Consultants</li>
          <li>Has taught several insurance courses at university level;  
            conducts seminars for professional organizations at national and state 
      levels </li>
	  
<hr>

<h3 style="color:Maroon;">Noreen M. Klink</h3>
<hr>

<%= image_tag("noreen.jpg", size: "100x113", :style => 'position: relative;',:style => "border: 3px solid Maroon")%>
<p>  </p>
      
          <li>Twenty-nine  years experience with national insurance underwriting and brokerage  organizations</li>
          <li>Seven years teaching, research and program administration at Midwest University  insurance and risk management program</li>
          <li>Chartered Property Casualty Underwriter  (CPCU)</li>
          <li> Associate in Risk Management (ARM)</li>
          <li>DePaul  University (BS); Loyola University (MBA)</li>
          <li>Former  Editor <em>Risk Management Quarterly</em> and Chairman, Risk Management Section,  CPCU Society</li>
        
<hr>

<h3 style="color:Maroon;">Steven H. Pahl</h3>
<hr>

<%= image_tag("steven2", size: "100x113", :style => 'position: relative;',:style => "border: 3px solid Maroon")%>
<p>  </p>
        
          <li>Twenty-nine  years experience with national insurance underwriting and brokerage  organizations</li>
          <li>Seven years teaching, research and program administration at Midwest University  insurance and risk management program</li>
          <li>Chartered Property Casualty Underwriter  (CPCU)</li>
          <li> Associate in Risk Management (ARM)</li>
          <li>DePaul  University (BS); Loyola University (MBA)</li>
          <li>Former  Editor <em>Risk Management Quarterly</em> and Chairman, Risk Management Section,  CPCU Society</li>
        
<hr>

<h3 style="color:Maroon;">Robert J. Trompeter</h3>
<hr>

<%= image_tag("robert.jpg", size: "100x113", :style => 'position: relative;',:style => "border: 3px solid Maroon")%>
<p>  </p>

        <li>Twenty-seven years insurance/risk management consulting</li>
        <li>Seven years prior experience with international insurance company 
          as an underwriter and supervisor-branch underwriting operations</li>
        <li> Eastern Illinois University (BS) </li>
        <li>Associate in Risk Management (ARM)</li>
       
<hr>






            
    
        

app/views/layouts/_footer.html.erb
 <footer class="footer">
      <div class="container">
        <span class="text-muted">Copyright &copy; 2017, Risk Resources, Inc. All Rights Reserved</span>
      </div>
    </footer>

app/views/layouts/_header.html.erb

<table bgcolor=''> <tr>
	<td width='10%' align='left'>
		<%= link_to (image_tag 'logo.png', size: "250x100"), home_about_path%></td> 

</tr></table>



            
       <!DOCTYPE html>

<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <ul class="nav navbar-nav">
        
   
       <%= link_to "Front Page ", home_about_path %>
<%= link_to "Company Profile ", home_company_path %> 
<%= link_to "Services Provided ", home_services_path %> 
    <%= link_to "Litigation Support ", home_litigation_path %> 
    <%= link_to "Professional Staff ", home_staff_path %> 
     <%= link_to "Contact Us ", home_contact_path %> 
    </ul>
  </div>
</nav>
  

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Risk Resources</title>
    <%= csrf_meta_tags %>

   
  </head>

  <body bgcolor='LightGray'>
<center>
    <table bgcolor='white' width='90%'>
    <tr><td><%= render "layouts/header" %></td></tr>
    <tr><td height='300' valign='top'><%= yield %></td></tr>
    <tr><td><%= render "layouts/footer" %></td> </tr>
    </table>
</center>
</body>
  
  
  
  
  
  
  
  
 
</html>